CC=gcc
CFLAGS=-I

turtles: turtles.c stack.c my_sdl_setup.c stack_generic.c testing.c infix_converter.c
	$(CC) -pedantic -Wall -std=c99 -o turtles turtles.c stack.c my_sdl_setup.c stack_generic.c testing.c infix_converter.c -framework SDL2 -I.